"""changed latitude & longitude to nullable

Revision ID: 340150a5b8e7
Revises: 811d2edc2b4d
Create Date: 2024-09-03 19:27:37.707793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '340150a5b8e7'
down_revision: Union[str, None] = '811d2edc2b4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stations', 'longitude',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('stations', 'latitude',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stations', 'latitude',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('stations', 'longitude',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
