"""neighbours ids to nullable

Revision ID: 34aacbe93c0a
Revises: 22c6152a662e
Create Date: 2024-09-04 13:16:40.779795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34aacbe93c0a'
down_revision: Union[str, None] = '22c6152a662e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stations', 'first_neighbour_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('stations', 'second_neighbour_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('stations_second_neighbour_id_fkey', 'stations', type_='foreignkey')
    op.drop_constraint('stations_first_neighbour_id_fkey', 'stations', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('stations_first_neighbour_id_fkey', 'stations', 'stations', ['first_neighbour_id'], ['id'])
    op.create_foreign_key('stations_second_neighbour_id_fkey', 'stations', 'stations', ['second_neighbour_id'], ['id'])
    op.alter_column('stations', 'second_neighbour_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('stations', 'first_neighbour_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
