"""updated models

Revision ID: 811d2edc2b4d
Revises: 9e6f1a7c1e02
Create Date: 2024-08-08 17:50:18.763044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '811d2edc2b4d'
down_revision: Union[str, None] = '9e6f1a7c1e02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cities', sa.Column('name_eng', sa.String(), nullable=False))
    op.add_column('cities', sa.Column('alias', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'cities', ['id'])
    op.add_column('lines', sa.Column('alias', sa.String(), nullable=False))
    op.add_column('lines', sa.Column('logo_path', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'lines', ['id'])
    op.create_unique_constraint(None, 'stations', ['id'])
    op.create_unique_constraint(None, 'user_favourite_stations', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_favourite_stations', type_='unique')
    op.drop_constraint(None, 'stations', type_='unique')
    op.drop_constraint(None, 'lines', type_='unique')
    op.drop_column('lines', 'logo_path')
    op.drop_column('lines', 'alias')
    op.drop_constraint(None, 'cities', type_='unique')
    op.drop_column('cities', 'alias')
    op.drop_column('cities', 'name_eng')
    # ### end Alembic commands ###
