version: '3.9'

services:
  metro_alarm_server_map:
    build:
      dockerfile: ./docker/Dockerfile.dev
      context: ../
    env_file:
      - ../.env/.dev.env
    command: ["/app/scripts/app.sh"]
    volumes:
      - ../alembic/versions:/app/alembic/versions
      - ../maps:/app/maps
      - ../logs:/app/logs
    depends_on:
      postgres_map:
        condition: service_healthy
    ports:
      - "80:8080"
    networks:
      - msa


  postgres_map:
    image: postgres:16.1-alpine3.19
    restart: always
    env_file:
      - ../.env/.database.dev.env
    volumes:
      - ../postgres/data:/var/lib/postgresql/data
      - ../postgres/postgresql.conf:/etc/postgresql/postgresql.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - msa


networks:
  msa:
    driver: bridge
    external: true
