FROM python:3.12-alpine

WORKDIR /app

COPY nginx/metro_alarm_server.csr /app/

COPY poetry.lock pyproject.toml /app/
RUN poetry config virtualenvs.create false && poetry install --no-dev --no-interaction --no-ansi

COPY stations /app

COPY alembic /app/alembic
COPY alembic.ini /app/alembic.ini
COPY scripts/app.sh /app/scripts/app.sh